# Generated by Django 5.1.6 on 2025-02-15 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='Image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='img_src/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pic',
            name='Month',
            field=models.CharField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pic',
            name='Year',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
