# Generated by Django 5.1.6 on 2025-02-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0010_alter_pic_month_alter_pic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='Month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=9),
        ),
    ]
